# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17e49fb6f5bc1c40f922e01a36a3c3881fbedfe7e0c04fdaaf43e0f49709920a7b1056d9ba63227898bd43e4cb645a4d9a65f1f2f1916eeaa2501d021a538c84

test:
  secret_key_base: 3dee3fd70c0deb4cd9aceaa987cb94474e2406a9f9a061d2c8da05c404a78e223c24fac18d11704b578d108ef5e9bd247b19708251f13383972f8e23db67bcc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
